name: RAISE

channels:
 - defaults
 - conda-forge

dependencies:
 - python == 3.10
 - pip
 - ipykernel
 - pillow
 - pip:
   - asyncio
   - opencv-python
   - numpy
   - pandas
   - numpy
   - baybe
   - scikit-image
   -TODO ADD NORTH
   


