accuracy_weight: 0.5
adaptive_deviation_threshold: 10.0
adaptive_penalty_variability: 100.0
liquid: glycerol
max_measurements: 96
min_good_parameter_sets: 6
precision_measurements: 3
precision_weight: 0.4
sim_dev_multiplier: 2.0
sim_var_multiplier: 2.0
simulate: false
time_weight: 0.1
timestamp: '20251030_154440'
vial_mode: legacy
volumes:
- 0.05
- 0.025
- 0.1
workflow_type: simplified
