experiment:
  liquid: PVA_water
  max_measurements_per_volume: 50
  max_total_measurements: 200
  simulate: false
  volume_targets_ml:
  - 0.1
hardware_parameters:
  aspirate_speed:
    bounds:
    - 5.0
    - 15.0
    type: discrete
  aspirate_wait_time:
    bounds:
    - 0.0
    - 0.0
    type: continuous
  blowout_vol:
    bounds:
    - 0.0
    - 0.0
    type: continuous
  dispense_speed:
    bounds:
    - 5.0
    - 15.0
    type: discrete
  dispense_wait_time:
    bounds:
    - 0.0
    - 0.0
    type: continuous
  post_asp_air_vol:
    bounds:
    - 0.0
    - 0.0
    type: continuous
  post_retract_wait_time:
    bounds:
    - 0.0
    - 0.0
    type: continuous
  pre_asp_air_vol:
    bounds:
    - 0.0
    - 0.0
    type: continuous
  retract_speed:
    bounds:
    - 2.5
    - 7.5
    type: discrete
optimization:
  enabled: true
  min_good_trials: 3
  strategy: qNEHVI
